# Generated by Django 5.1.3 on 2024-12-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
